# only needed for local testing with multiple redis instances, not needed for production since we will use ElastiCache Redis Cluster (AWS)
version: '3.8'

services:
  redis1:
    image: redis:7
    ports:
      - "6379:6379"

  redis2:
    image: redis:7
    ports:
      - "6380:6379"

  redis3:
    image: redis:7
    ports:
      - "6381:6379"